### ISSUE TITLE
Wangle doesn't compile with fresh folly

### ISSUE THREAD

**Issue by vadimkantorov** [facebook/wangle#10]
Hi,

It seems the operator-> (https://github.com/facebook/folly/blob/e845ef57f1f368944123e4a50bd4d1616a363efa/folly/Singleton.h#L453) was removed at some point, so wangle compiles no more.

By fresh folly I mean commit 8f1e662a59dec3476bf626b283effaa8a88acdd5 (and Singleton.h https://github.com/facebook/folly/blob/8f1e662a59dec3476bf626b283effaa8a88acdd5/folly/Singleton.h).

Vadim

**Comment by vadimkantorov** [comment]
I could fix the compilation by replacing "->" to ".get()->" on line 62 of wangle/concurrent/GlobalExecutor.cpp

**Comment by djwatson** [comment]
Wangle was pushed, should be fixed?
