### ISSUE TITLE
Consider re-licensing to AL v2.0, as RocksDB has just done

### ISSUE THREAD

**Issue by enis** [facebook/wangle#105]
Hi, 

The Apache Software Foundation Legal Affairs Committee has announced that the so-called 'Facebook BSD+Patents License' is no longer allowed to be used as a direct dependency in Apache projects.

This has lead to a lot of upset and frustration in the Apache community, especially from projects requiring similarly-licensed code as direct dependencies - the chief of these being RocksDB.

However, we (the Apache Software Foundation) have just received word that RocksDB will be re-licensing their code under the dual Apache License v2.0 and GPL 2 licenses (https://github.com/facebook/rocksdb/pull/2589). 

Apache HBase C++ client (HBASE-14850) depends on folly and wangle for implementing async socket IO and async RPC framework. We would kindly ask Wangle to change the license to be an ASF-compatible license, otherwise, as many ASF projects, we have no option but to stop using Wangle. 

Please note that folly itself is using Apache License 2.0, and RocksDB have decided to switch their licenses to be the same, and React is deciding on the option: 
https://github.com/facebook/rocksdb/pull/2589
https://github.com/facebook/react/issues/10191

Thank you kindly for your consideration.

**Comment by yfeldblum** [comment]
Thanks for opening the issue. In 5f686dee5753890f37326fcf38c396b7ba8981ee, which is in the history of `master`, the Wangle license is changed to Apache License 2.0. This license change will be included in the next weekly release tag.

**Comment by enis** [comment]
Thanks @yfeldblum and others. This is really great that, and unblocks us in the HBase community.

**Comment by lukecwilliams** [comment]
@yfeldblum This is great.  Can you provide any info on why Wangle was able to go a different direction from most of the Facebook open source ecosystem on this issue?
