### ISSUE TITLE
Waggle dependency on folly: folly/portability/Sockets.h: No such file or directory

### ISSUE THREAD

**Issue by jpilaul** [facebook/wangle#110]
Hi I am building wangle locally and I am getting the following error:

`[  1%] Building CXX object CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o
In file included from /idiap/user/lmiculicich/Installations/wangle/wangle/../wangle/acceptor/AcceptorHandshakeManager.h:18:0, from /idiap/user/lmiculicich/Installations/wangle/wangle/../wangle/acceptor/PeekingAcceptorHandshakeHelper.h:12,
from /idiap/user/lmiculicich/Installations/wangle/wangle/../wangle/acceptor/SecurityProtocolContextManager.h:12,
from /idiap/user/lmiculicich/Installations/wangle/wangle/../wangle/acceptor/Acceptor.h:17,
from /idiap/user/lmiculicich/Installations/wangle/wangle/acceptor/Acceptor.cpp:10:
/idiap/user/lmiculicich/Installations/wangle/wangle/../wangle/acceptor/TransportInfo.h:18:39: fatal error: folly/portability/Sockets.h: No such file or directory
 #include <folly/portability/Sockets.h>
                                       ^
compilation terminated.
CMakeFiles/wangle.dir/build.make:62: recipe for target 'CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o' failed
make[2]: *** [CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o] Error 1
CMakeFiles/Makefile2:598: recipe for target 'CMakeFiles/wangle.dir/all' failed
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

wangle version: 3:0
folly version: 7:0
Linux helvetix16 3.16.0-4-amd64 
Debian 3.16.43-2+deb8u2 
x86_64 GNU/Linux

I can't `sudo ldconfig` because I don't have admin rights.

Thanks

**Comment by vedhasd91** [comment]
are the Folly libpath and include dir set to where it is installed on your system? if not do in cmake/FindFolly.cmake:

`set(FOLLY_LIBRARYDIR /path/to/your/lib)`

`set(FOLLY_INCLUDEDIR /path/to/folly/includes)`

**Comment by yfeldblum** [comment]
Too old.
