### ISSUE TITLE
Example usage for IOThreadpool?

### ISSUE THREAD

**Issue by vedhasd91** [facebook/wangle#111]
I am currently using IOThreadpool as a member of a class, and periodically add IO task to the queue, it works fine when it is periodic with certain seconds. When I add aperiodic tasks, the IOThreadPool madvises the stack, but I end getting this:

`detail/MemoryIdler.cpp:159: static void folly::detail::MemoryIdler::unmapUnusedStack(size_t): Assertion `(*__errno_location ()) == 11 || (*__errno_location ()) == 12' failed.`

somewhere in main:
`A a()
...
a.AddTask()`

`class A{
...
private:
wangle::IOThreadPoolExecutor thread_pool_;
}`

`A() : ...,
       : thread_pool_(1)`

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
