### ISSUE TITLE
example/proxy  crash on uninitialized backendPipeline_ of the ProxyFrontendHandler

### ISSUE THREAD

**Issue by bluestn** [facebook/wangle#115]
In the example/Proxy.cpp,  class ProxyFrontendHandler has the uninitialized DefaultPipeline* backendPipeline_, this will cause ProxyServer crash occasionally.

fix:
  
  DefaultPipeline* backendPipeline_{nullptr};

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
