### ISSUE TITLE
`CALLBACK` is a macro for `__stdcall` or `__cdecl` on Windows.

### ISSUE THREAD

**Issue by capsocrates** [facebook/wangle#116]
https://github.com/facebook/wangle/blob/095f6bbf071c38ad4f9ad65556910ee31dece811/wangle/acceptor/EvbHandshakeHelper.h#L66

This line does not compile on Windows, as a calling convention is not a valid enum member, and the compiler replaces `CALLBACK` with either `__stdcall` or `__cdecl`.

**Comment by yfeldblum** [comment]
Fixed in 5c4935af43cce64487458e10dc7ebd609ad7692b.
