### ISSUE TITLE
Build failing on ubuntu

### ISSUE THREAD

**Issue by ghost** [facebook/wangle#117]
Hello,

i am having trouble building Wangle on Ubuntu 16.04. I have installed all of the dependencies, linked Folly and even ssl and crypto, but still i am getting linker error:

> /usr/bin/ld: ../third_party/wangle/bin/usr/local/lib/libwangle.a(SSLSessionCacheManager.cpp.o): undefined reference to symbol 'SSL_CTX_sess_set_remove_cb@@OPENSSL_1.0.0'
> /lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line

I have no idea what am I missing. Can anyone help me please?

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
