### ISSUE TITLE
cmake . error ?

### ISSUE THREAD

**Issue by yghcats** [facebook/wangle#124]
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  REQUIRED_ARGS (missing: FOLLY_INCLUDE_DIR FOLLY_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFolly.cmake:23 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:22 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/launchx-mask/crnn/wangle/wangle/CMakeFiles/CMakeOutput.log".

**Comment by quanpinjie** [comment]
i meet this error, do you have any solution?

**Comment by yfeldblum** [comment]
Closing this issue because it is too old.
