### ISSUE TITLE
FileRegionReadPool BUG

### ISSUE THREAD

**Issue by alexliyu7352** [facebook/wangle#128]
When I run then FileServer example, It is shows

F0418 04:36:35.498564 16180 Singleton.cpp:149] Singleton N5folly20IOThreadPoolExecutorE/N12_GLOBAL__N_118FileRegionReadPoolE requested before registrationComplete() call.
This usually means that either main() never called folly::init, or singleton was requested before main() (which is not allowed).

**Comment by yfeldblum** [comment]
I can fix this shortly.
