### ISSUE TITLE
ctest errors

### ISSUE THREAD

**Issue by lixiangnlp** [facebook/wangle#14]
Test project /home/lixiang/library/facebook/wangle-master/wangle/build
      Start  1: AcceptorTest
 1/15 Test  #1: AcceptorTest .........................   Passed    0.02 sec
      Start  2: LoadShedConfigurationTest
 2/15 Test  #2: LoadShedConfigurationTest ............   Passed    0.01 sec
      Start  3: PeekingAcceptorHandshakeHelperTest
 3/15 Test  #3: PeekingAcceptorHandshakeHelperTest ...   Passed    0.02 sec
      Start  4: BootstrapTest
 4/15 Test  #4: BootstrapTest ........................   Passed    0.64 sec
      Start  5: AsyncSocketHandlerTest
 5/15 Test  #5: AsyncSocketHandlerTest ...............   Passed    0.01 sec
      Start  6: OutputBufferingHandlerTest
 6/15 Test  #6: OutputBufferingHandlerTest ...........   Passed    0.01 sec
      Start  7: PipelineTest
 7/15 Test  #7: PipelineTest .........................   Passed    0.27 sec
      Start  8: CodecTest
 8/15 Test  #8: CodecTest ............................   Passed    0.00 sec
      Start  9: CodelTest
 9/15 Test  #9: CodelTest ............................   Passed    0.58 sec
      Start 10: GlobalExecutorTest
10/15 Test #10: GlobalExecutorTest ...................   Passed    0.00 sec
      Start 11: ThreadPoolExecutorTest
11/15 Test #11: ThreadPoolExecutorTest ...............   Passed    0.69 sec
      Start 12: RxTest
12/15 Test #12: RxTest ...............................   Passed    0.01 sec
      Start 13: ServiceTest
13/15 Test #13: ServiceTest ..........................***Exception: SegFault  0.07 sec
      Start 14: SSLCacheTest
14/15 Test #14: SSLCacheTest .........................***Failed    0.00 sec
      Start 15: SSLContextManagerTest
15/15 Test #15: SSLContextManagerTest ................   Passed    0.00 sec

87% tests passed, 2 tests failed out of 15

Total Test time (real) =   2.34 sec

The following tests FAILED:
	 13 - ServiceTest (SEGFAULT)
	 14 - SSLCacheTest (Failed)
Errors while running CTest

Do you know why?

**Comment by qyouurcs** [comment]
I have the same problem. ServiceTest and SSLCacheTest failed.

The platform is Fedora 20.

**Comment by djwatson** [comment]
I disabled these tests for now.  Thanks
