### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by bluestn** [facebook/wangle#142]
CMake Error at CMakeLists.txt:105 (add_library):
  Target "wangle" links to target "glog::glog" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

How does glog::glog appear here?
Maybe only glog, right?

**Comment by draft6** [comment]
@bluestn Did you solve this in the end? Just tryed compiling the new version and am getting the same thing.
