### ISSUE TITLE
 folly::ssl::SSLSessionUniquePtr is not a member, build on mac

### ISSUE THREAD

**Issue by 8427003** [facebook/wangle#146]
i can't find SSLSessionUniquePtr class in folly source code.What is this black technology.
![buildfail](https://user-images.githubusercontent.com/5475231/51796919-bf52da80-2235-11e9-989f-ff749a41ed4b.jpeg)

**Comment by yfeldblum** [comment]
It's in [`folly/ssl/OpenSSLPtrTypes.h`](https://github.com/facebook/folly/blob/v2019.03.04.00/folly/ssl/OpenSSLPtrTypes.h#L113).
