### ISSUE TITLE
wangle find_package does not work on windows vcpkg

### ISSUE THREAD

**Issue by soroshsabz** [facebook/wangle#148]
ITNOA

When I want to use wangle on windows, in `CMakeLists.txt` I write below code:

`find_package(wangle CONFIG REQUIRED)`

and see below error

```
CMake Error at C:/Users/sooro/Documents/vcpkg/vcpkg/installed/x64-windows/share/wangle/wangle-config.cmake:22 (message):
  File or directory
  C:/Users/sooro/Documents/vcpkg/vcpkg/installed/x64-windows/lib/cmake/wangle
  referenced by variable WANGLE_CMAKE_DIR does not exist !
Call Stack (most recent call first):
  C:/Users/sooro/Documents/vcpkg/vcpkg/installed/x64-windows/share/wangle/wangle-config.cmake:39 (set_and_check)
  C:/Users/sooro/Documents/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:258 (_find_package)
  CMakeLists.txt:44 (find_package) 
```

I use vcpkg toolchain, did you have any idea to resolve my problem?

best reqards

**Comment by Orvid** [comment]
It sounds like the vcpkg config for wangle isn't fixing up the config after moving it into `share/wangle`, so you'll want to fix that upstream in the wangle config (we don't actually maintain the vcpkg configs for wangle)

**Comment by soroshsabz** [comment]
@Orvid Ok that's right

thanks
