### ISSUE TITLE
compiling  failure when building AsyncSocketHandlerTest.cpp.o on Ubuntu 14.04

### ISSUE THREAD

**Issue by zach-yu** [facebook/wangle#15]
It seems that lasted folly has make Future copy ctor deleted, which is used in AsyncSocketHandlerTest.cpp.
>Scanning dependencies of target AsyncSocketHandlerTest
[  2%] Building CXX object CMakeFiles/AsyncSocketHandlerTest.dir/channel/test/AsyncSocketHandlerTest.cpp.o
In file included from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock-generated-function-mockers.h:43:0,
                 from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock.h:61,
                 from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/../wangle/channel/test/MockHandler.h:13,
                 from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/channel/test/AsyncSocketHandlerTest.cpp:14:
/home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock-spec-builders.h: In instantiation of ‘T testing::internal::ActionResultHolder<T>::GetValueAndDelete() const [with T = folly::Future<folly::Unit>]’:
/home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock-spec-builders.h:1530:60:   required from ‘testing::internal::FunctionMockerBase<F>::Result testing::internal::FunctionMockerBase<F>::InvokeWith(const ArgumentTuple&) [with F = folly::Future<folly::Unit>(wangle::HandlerContext<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf> >*, std::shared_ptr<folly::IOBuf>); testing::internal::FunctionMockerBase<F>::Result = folly::Future<folly::Unit>; testing::internal::FunctionMockerBase<F>::ArgumentTuple = std::tuple<wangle::HandlerContext<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> > >*, std::shared_ptr<folly::IOBuf> >]’
/home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock-generated-function-mockers.h:118:50:   required from ‘R testing::internal::FunctionMocker<R(A1, A2)>::Invoke(A1, A2) [with R = folly::Future<folly::Unit>; A1 = wangle::HandlerContext<folly::IOBufQueue&, std::unique_ptr<folly::IOBuf> >*; A2 = std::shared_ptr<folly::IOBuf>]’
/home/zed/fbthrift/thrift/build/deps/wangle/wangle/../wangle/channel/test/MockHandler.h:73:3:   required from here
/home/zed/fbthrift/thrift/build/deps/wangle/wangle/gmock/src/gmock/include/gmock/gmock-spec-builders.h:1330:20: error: use of deleted function ‘folly::Future<T>::Future(const folly::Future<T>&) [with T = folly::Unit]’
     T retval(value_);
                    ^
In file included from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/../wangle/channel/Handler.h:13:0,
                 from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/../wangle/channel/AsyncSocketHandler.h:13,
                 from /home/zed/fbthrift/thrift/build/deps/wangle/wangle/channel/test/AsyncSocketHandlerTest.cpp:12:
/usr/local/include/folly/futures/Future.h:50:3: error: declared here
   Future(Future const&) = delete;

**Comment by djwatson** [comment]
should be fixed

**Comment by abhiguru** [comment]
I am getting a similar error no in AsyncHandler but on using folly::via(executor, ...) code here https://gist.github.com/abhiguru/d90bae044c6a06e2e742
Error details here https://gist.github.com/abhiguru/7a35edeb54c0870e4850 does it seem related? Or a separate issue is needed ?
