### ISSUE TITLE
Checking if file exists before reading can cause problem in case of race conditions.

### ISSUE THREAD

**Issue by farziengineer** [facebook/wangle#154]
https://github.com/facebook/wangle/blob/cc46c238641eab405eb15ff14a693128f463a465/build/fbcode_builder/getdeps/fetcher.py#L390-L391

The above snippet of code can cause problem in case of race condition, where file might be present at the time of `if os.path.exists(path)` but might not exist when we try to read the file and result in exception. The python EAFP(Easy to Ask for Forgiveness than Permission) philosophy suggests that we use a try catch block to avoid this problem. [Suggested changes](https://stackoverflow.com/a/56036903/8577285).
You can read [this stackoverflow answer ](https://stackoverflow.com/a/82852/8577285) to understand the problem more 
Can this issue be assigned to me? 
The above snippet can be replaced by the following.
```python
try:
    f = open(config_file)
except IOError as e:
    print("File can't be accessed")
else:
      with f:
             remaining code
              ...
              ...

@wez 
@yfeldblum

**Comment by yfeldblum** [comment]
This build system should not be used concurrently with other programs which can modify the build system's filesystem state.

But if the user insists on using it that way and the build system fails with a raised exception, the user may simply retry.
