### ISSUE TITLE
failed to install wangle on windows with vcpkg install wangle command

### ISSUE THREAD

**Issue by gwnet** [facebook/wangle#184]
[DEBUG] CreateProcessW("C:\Program Files\CMake\bin\cmake.exe" -DPORT=boost-compatibility -DCURRENT_PORT_DIR=C:/Wayne/vcpkg/ports/boost-compatibility -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_NO_DOWNLOADS=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -DFEATURES=core -DALL_FEATURES= -DCMD=BUILD -DTARGET_TRIPLET=x86-windows "-DTARGET_TRIPLET_FILE=C:\Wayne\vcpkg\triplets\x86-windows.cmake" -DVCPKG_PLATFORM_TOOLSET=v142 -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_CONCURRENCY=9 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/Wayne/vcpkg -DPACKAGES_DIR=C:/Wayne/vcpkg/packages -DBUILDTREES_DIR=C:/Wayne/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Wayne/vcpkg/installed -DDOWNLOADS=C:/Wayne/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Wayne\vcpkg\scripts\ports.cmake")
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.74.0.tar.gz... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:182 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:143 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:136 (include)

[DEBUG] cmd_execute_and_stream_data() returned 1 after 21536643 us
Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
[DEBUG] C:\Wayne\vcpkg\toolsrc\src\vcpkg\install.cpp(494)
[DEBUG] Exiting after 35642863 us (35627130 us)

C:\Wayne\vcpkg>

**Comment by ras0219** [comment]
This looks like a temporary issue downloading boost and isn't an issue with wangle. I recommend closing this issue and @gwnet please reopen in Microsoft/vcpkg if this is still a problem.
