### ISSUE TITLE
very poor performance with echo example

### ISSUE THREAD

**Issue by gwnet** [facebook/wangle#185]
hello guys,

I change echo example code a little bit. I let client keep send 4K String, I want to measure the performance for wangle, but I see the performance is truly bad. 

below is sar result.
./bin/EchoClient --host=127.0.0.1
./bin/EchoServer 

08:52:11 AM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
08:52:13 AM   docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM    ens3f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM enp24s0f2      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM enp24s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM    ens3f0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM        lo   1791.50   1791.50   6718.22   6718.22      0.00      0.00      0.00      0.00
08:52:13 AM enp24s0f3      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
08:52:13 AM enp24s0f0     20.50     23.50      1.44      3.17      0.00      0.00      0.00      0.00
^C

Average:        IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s   %ifutil
Average:      docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:       ens3f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    enp24s0f2      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    enp24s0f1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:       ens3f0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:           lo   1763.32   1763.32   6685.85   6685.85      0.00      0.00      0.00      0.00
Average:    enp24s0f3      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    enp24s0f0     22.61     24.57      1.69      3.30      0.00      0.00      0.85      0.00

**Comment by dreamofboy** [comment]
This is a failed open source project? 
Very poor documentations. Inactive community.
