### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by helloleef** [facebook/wangle#2]
[  4%] Building CXX object CMakeFiles/wangle.dir/codec/LengthFieldPrepender.cpp.o
In file included from /usr/local/include/folly/futures/Promise-inl.h:23:0,
                 from /usr/local/include/folly/futures/Promise.h:115,
                 from /usr/local/include/folly/futures/Future.h:30,
                 from /home/leef/download/wangle/wangle/../wangle/channel/Handler.h:13,
                 from /home/leef/download/wangle/wangle/../wangle/codec/ByteToMessageCodec.h:13,
                 from /home/leef/download/wangle/wangle/../wangle/codec/LengthFieldPrepender.h:13,
                 from /home/leef/download/wangle/wangle/codec/LengthFieldPrepender.cpp:11:
/usr/local/include/folly/futures/detail/Core.h: In instantiation of ‘class folly::detail::Core<void>’:
/usr/local/include/folly/futures/Future-inl.h:64:5:   required from ‘void folly::Future<T>::detach() [with T = void]’
/usr/local/include/folly/futures/Future-inl.h:58:10:   required from ‘folly::Future<T>::~Future() [with T = void]’
/home/leef/download/wangle/wangle/codec/LengthFieldPrepender.cpp:90:39:   required from here
/usr/local/include/folly/futures/detail/Core.h:77:3: error: static assertion failed: void futures are not supported. Use Unit instead.
   static_assert(!std::is_void<T>::value,
   ^
make[2]: *** [CMakeFiles/wangle.dir/codec/LengthFieldPrepender.cpp.o] Error 1
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmatheny** [comment]
cc @jsedgwick

**Comment by viswanathgs** [comment]
This is because of the void to folly::Unit refactor that got pushed to https://github.com/facebook/folly, which breaks Wangle. This should be fixed when Wangle gets pushed next.

**Comment by bmatheny** [comment]
@helloleef looking good?
