### ISSUE TITLE
error:relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE

### ISSUE THREAD

**Issue by NoobPythoner** [facebook/wangle#236]
I encountered the following issue while compiling the code: 
#68 94.61 /usr/bin/ld: /usr/local/lib/libgmock.a(gmock-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
#68 94.61 /usr/bin/ld: failed to set dynamic section sizes: bad value
#68 94.62 collect2: error: ld returned 1 exit status
#68 94.63 make[2]: *** [CMakeFiles/ConnectionManagerTest.dir/build.make:148：bin/ConnectionManagerTest] 错误 1
#68 94.63 make[1]: *** [CMakeFiles/Makefile2:139：CMakeFiles/ConnectionManagerTest.dir/all] 错误 2
#68 94.63 make: *** [Makefile:166：all] 错误 2

How I  can  solve it？

**Comment by NoobPythoner** [comment]
Can anyone provide help?

**Comment by yfeldblum** [comment]
This does not seem like the type of issue in which we would have expertise or with which we would be able to help.
