### ISSUE TITLE
LifoSemMPMCQueue full, can't add item

### ISSUE THREAD

**Issue by abhiguru** [facebook/wangle#30]
What is the limit and how can one go about increasing it ?

**Comment by crackcomm** [comment]
Not sure what this is all about but this is a constructor:
```C++
explicit LifoSemMPMCQueue(size_t max_capacity)
````

**Comment by djwatson** [comment]
Correct, it can only be set at compile time.  We're working on some changes to make it dynamically sizeable currently.

**Comment by shashank88** [comment]
@djwatson was this ever resolved? I am hitting a similar issue via folly where I get: 
`folly::QueueFullException(LifoSemMPMCQueue full, can't add item)`
