### ISSUE TITLE
Compile failed on latest committed branch

### ISSUE THREAD

**Issue by phynalle** [facebook/wangle#31]
I tried to compile wangle on lastest commit whose hash is 0891263fd51df640531149ee1eac555210a8d3d9.

errors occur in SSLContextManagerTest.cpp: In member function ‘virtual void wangle::SSLContextManagerTest_TestSessionContextIfSupplied_Test::TestBody()’

but compile is succeeded on right before commit whose hash is 1ae9efd54efc8b437577f5585d6e068e709cd741.

I'm installing proxygen. it forced to change branch to master. so I cannot install it. Please fix it.

**Comment by anirudhvr** [comment]
@siyengar Want to take a look?

**Comment by anirudhvr** [comment]
Thanks for reporting, will fix this soon. Looks like it's the two ASSERT_TRUE(ctx) in SSLContextManagerTest.cpp lines 132 and 161, which you can change to ASSERT_TRUE(ctx != nullptr), you'd like to get unblocked.
