### ISSUE TITLE
Current build fails at BootstrapTest

### ISSUE THREAD

**Issue by mjs6643** [facebook/wangle#34]
Boost 1.60, GCC 5.3, Ubuntu 14.04

> [ 71%] Building CXX object CMakeFiles/BootstrapTest.dir/bootstrap/BootstrapTest.cpp.o
> Linking CXX executable bin/BootstrapTest
> /usr/bin/ld: CMakeFiles/BootstrapTest.dir/bootstrap/BootstrapTest.cpp.o: undefined reference to symbol '_ZN5boost10filesystem4pathdVERKS1_'
> /usr/local/lib/libboost_filesystem.so.1.60.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: **\* [bin/BootstrapTest] Error 1
> make[1]: **\* [CMakeFiles/BootstrapTest.dir/all] Error 2
> make: **\* [all] Error 2

**Comment by anirudhvr** [comment]
This seems like a library order issue in the link command (-lboost_Filesystem should come after the .o). Can you share the failed build command for BootstrapTest?

**Comment by VictorDegliame** [comment]
I fixed the issue by adding boost filesystem to CMakeLists.txt and created the following pull request:
https://github.com/facebook/wangle/pull/35

Hope that helps.

**Comment by anirudhvr** [comment]
Thanks! I'll merge it in shortly.
