### ISSUE TITLE
Problem when I make wangle in OSX

### ISSUE THREAD

**Issue by NivasCbe** [facebook/wangle#37]
After cmake . I face the following problem when I try to make. PFB the logs of the same.

[ 49%] Building CXX object CMakeFiles/BroadcastHandlerTest.dir/channel/broadcast/test/BroadcastHandlerTest.cpp.o
In file included from /Users/nivas.thangavelu/code/wangle/wangle/channel/broadcast/test/BroadcastHandlerTest.cpp:10:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/test/Mocks.h:15:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/BroadcastHandler.h:12:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/AsyncSocketHandler.h:13:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Handler.h:14:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Pipeline.h:22:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/acceptor/TransportInfo.h:12:
/Users/nivas.thangavelu/code/wangle/wangle/../wangle/ssl/SSLUtil.h:74:17: warning: 'SSL_CTX_get_ex_new_index' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
      _pindex = SSL_CTX_get_ex_new_index(0, nullptr, nullptr, nullptr, nullptr);
                ^
/usr/include/openssl/ssl.h:1614:5: note: 'SSL_CTX_get_ex_new_index' has been explicitly marked deprecated here
int SSL_CTX_get_ex_new_index(long argl, void *argp, CRYPTO_EX_new *new_func,
    ^
In file included from /Users/nivas.thangavelu/code/wangle/wangle/channel/broadcast/test/BroadcastHandlerTest.cpp:10:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/test/Mocks.h:15:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/BroadcastHandler.h:12:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/AsyncSocketHandler.h:13:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Handler.h:14:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Pipeline.h:22:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/acceptor/TransportInfo.h:12:
/Users/nivas.thangavelu/code/wangle/wangle/../wangle/ssl/SSLUtil.h:81:17: warning: 'RSA_get_ex_new_index' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
      *pindex = RSA_get_ex_new_index(0, nullptr, nullptr, nullptr, nullptr);
                ^
/usr/include/openssl/rsa.h:389:5: note: 'RSA_get_ex_new_index' has been explicitly marked deprecated here
int RSA_get_ex_new_index(long argl, void *argp, CRYPTO_EX_new *new_func,
    ^
In file included from /Users/nivas.thangavelu/code/wangle/wangle/channel/broadcast/test/BroadcastHandlerTest.cpp:10:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/test/Mocks.h:15:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/broadcast/BroadcastHandler.h:12:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/AsyncSocketHandler.h:13:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Handler.h:14:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/channel/Pipeline.h:22:
In file included from /Users/nivas.thangavelu/code/wangle/wangle/../wangle/acceptor/TransportInfo.h:12:
/Users/nivas.thangavelu/code/wangle/wangle/../wangle/ssl/SSLUtil.h:121:17: warning: 'SSL_SESSION_get_ex_new_index' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
      *pindex = SSL_SESSION_get_ex_new_index(
                ^
/usr/include/openssl/ssl.h:1609:5: note: 'SSL_SESSION_get_ex_new_index' has been explicitly marked deprecated here
int SSL_SESSION_get_ex_new_index(long argl, void *argp, CRYPTO_EX_new *new_func,
    ^
3 warnings generated.
[ 49%] Linking CXX executable bin/BroadcastHandlerTest
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *_\* [bin/BroadcastHandlerTest] Error 1
make[1]: **\* [CMakeFiles/BroadcastHandlerTest.dir/all] Error 2
make: **\* [all] Error 2

**Comment by anirudhvr** [comment]
The SSL warnings are because Apple has "deprecated" OpenSSL for some time. This doesn't mean anything other than you should probably verify which version of OpenSSL is being linked in, and perhaps install your own using homebrew. 

The actual error is that the linker can't find -latomic. I don't believe wangle is "officially" supported on OS X, but since this is part of C++11, can you try removing '-latomic' from CMakeLists and try?

**Comment by bithavoc** [comment]
After removing -latomic from Cmakelist I got:

```
[ 72%] Building CXX object CMakeFiles/AsyncTest.dir/concurrent/test/AsyncTest.cpp.o
In file included from /Users/bithavoc/Documents/Projects/wangle/wangle/concurrent/test/AsyncTest.cpp:12:
/Users/bithavoc/Documents/Projects/wangle/wangle/../wangle/concurrent/Async.h:18:1: error: 'auto' return without trailing return type; deduced return
      types are a C++14 extension
auto async(F&& fn) {
^
/Users/bithavoc/Documents/Projects/wangle/wangle/concurrent/test/AsyncTest.cpp:22:12: error: no matching function for call to 'async'
  auto f = async([]{ return 42; });
           ^~~~~
/Users/bithavoc/Documents/Projects/wangle/wangle/concurrent/test/AsyncTest.cpp:31:17: error: no matching function for call to 'async'
  auto future = async(lambda);
                ^~~~~
/Users/bithavoc/Documents/Projects/wangle/wangle/concurrent/test/AsyncTest.cpp:37:17: error: no matching function for call to 'async'
  auto future = async(lambda);
                ^~~~~
/Users/bithavoc/Documents/Projects/wangle/wangle/concurrent/test/AsyncTest.cpp:44:17: error: no matching function for call to 'async'
  auto future = async(lambda);
                ^~~~~
5 errors generated.
make[2]: *** [CMakeFiles/AsyncTest.dir/concurrent/test/AsyncTest.cpp.o] Error 1
make[1]: *** [CMakeFiles/AsyncTest.dir/all] Error 2
make: *** [all] Error 2
```
any tips?

**Comment by snarkmaster** [comment]
@bithavoc, it says "types are a C++14 extension". Does your compiler speak C++14?

**Comment by bithavoc** [comment]
it should
```
 g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Dalzhim** [comment]
Problem is the CMakeLists.txt file has the CXX Compiler Flags set to -std=c++11. Replace that with -std=c++14 and it'll compile fine. You can also check my pull request which fixes the OS X build : https://github.com/facebook/wangle/pull/47
