### ISSUE TITLE
Error compiling in Ubuntu 15.04

### ISSUE THREAD

**Issue by cronnosli** [facebook/wangle#4]
root@douglasnote:/home/douglas/projetos/filtro/lib/proxigen/proxygen/wangle/wangle# cmake .
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
-- Configuring done
-- Generating done
-- Build files have been written to: /home/douglas/projetos/filtro/lib/proxigen/proxygen/wangle/wangle

root@douglasnote:/home/douglas/projetos/filtro/lib/proxigen/proxygen/wangle/wangle# make
[ 18%] Built target gmock
[ 74%] Built target wangle
[ 76%] Built target BootstrapTest
[ 79%] Built target CodecTest
[ 81%] Built target CodelTest
[ 83%] Built target GlobalExecutorTest
[ 86%] Built target OutputBufferingHandlerTest
[ 88%] Built target PipelineTest
[ 90%] Built target RxTest
[ 93%] Built target SSLCacheTest
[ 95%] Built target SSLContextManagerTest
[ 97%] Building CXX object CMakeFiles/ServiceTest.dir/service/ServiceTest.cpp.o
/home/douglas/projetos/filtro/lib/proxigen/proxygen/wangle/wangle/service/ServiceTest.cpp: In function ‘int folly::main(int, char**)’:
/home/douglas/projetos/filtro/lib/proxigen/proxygen/wangle/wangle/service/ServiceTest.cpp:324:3: error: ‘ParseCommandLineFlags’ is not a member of ‘google’
   google::ParseCommandLineFlags(&argc, &argv, true);
   ^
make[2]: ** [CMakeFiles/ServiceTest.dir/service/ServiceTest.cpp.o] Erro 1
make[1]: ** [CMakeFiles/ServiceTest.dir/all] Erro 2
make: ** [all] Erro 2

uname -a
Linux douglasnote 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bmatheny** [comment]
@jsedgwick looks like gflags is missing, but since I think it's a dependency for glog are both missing? Not near a computer, will debug a bit more shortly.

**Comment by cronnosli** [comment]
I don't see this happen on Debian 8, both Debian 8 and Ubuntu 15.04 has glog and gflags dev packages installed. Perhaps something weird with the Ubuntu package dependencies?
Anyway I'll try to install gflags from source code.

**Comment by bmatheny** [comment]
This is a compile error not a link error; I'm surprised this worked at all unless the compilers are different. What compilers were you using?

**Comment by fugalh** [comment]
May be a missing implicit header that we need to explicitly include in that
test cpp file?

**Comment by bmatheny** [comment]
@fugalh yah, I'm wondering if just including the gflags header would be enough. I also noticed that `main()` is `folly::main()` :P

**Comment by tazio** [comment]
It's the same on OpenSUSE 13.2 - perhaps is it gflags::ParseCommandLineFlags and not google::ParseCommandLineFlags ?

**Comment by cronnosli** [comment]
This is very weird, but I made a fresh install and use gflags from source,
not the package from Ubuntu and this not happen. On Debian 8 both package
and source gflags, wangle compiles ok!

Anyway now I have wangle as a debian lib package.

Douglas M Cordeiro <cronnosli@gmail.com>.


2015-09-08 7:52 GMT-03:00 Tazio Ceri <notifications@github.com>:
