### ISSUE TITLE
G++ exhausted the memory while compiling Acceptor.cpp

### ISSUE THREAD

**Issue by guoxiao** [facebook/wangle#51]
My g++ version is
``` 
% g++ --version
g++ (GCC) 6.1.1 20160510 (Red Hat 6.1.1-2)
Copyright (C) 2016 Free Software Foundation, Inc.
```

I don't know if it's a bug of `g++` or it's a problem caused by the structure of `Acceptor.cpp`.

**Comment by djwatson** [comment]
How much memory did it use?

**Comment by guoxiao** [comment]
@djwatson It will use up all my 16GB memory and get killed by the kernel while compiling this file.

**Comment by djwatson** [comment]
I see ~1.5G taken for compilation, although that's on 4.8 or 5.  I'm guessing this is a gcc bug, but I'll leave this open until we know for sure.

**Comment by djwatson** [comment]
Also compiles fine with clang 3.9.0

**Comment by snarkmaster** [comment]
I have frequently built wangle and fbthrift and folly with GCC 4.8 on a 1.5GB VM. Only `fbthrift` gets close to running out of memory. I would guess that the new GCC is leaky or has an overly expensive optimization pass.

To measure memory usage of a process, you can try `/usr/bin/time FAILING COMMAND`. Look for `maxresident`.

**Comment by guoxiao** [comment]
The gcc-c++ from Fedora Rawhide has fixed the problem.

% g++ --version
g++ (GCC) 6.1.1 20160721 (Red Hat 6.1.1-4)
