### ISSUE TITLE
Latest wangle tag does not work against latest folly tag

### ISSUE THREAD

**Issue by zleho** [facebook/wangle#56]
Hi,

Latest tags from the projects are incompatible. I am using v2016.08.15.00 from folly and 0.13.0 from wangle. Could you please create a compatible tag for this folly version?

Thanks!

Br,
Zleho

**Comment by elliottneilclark** [comment]
New tags are created automatically. If there was some incompatibility at the time of tagging, the next tag should be good. Incompatibilities between tags should be pretty rare.

**Comment by zleho** [comment]
There were 5 automatically created tags on folly which is not compatible with wangle tag 0.13.0. Can you tell me when the next wangle tagging will happen? Master seems to be OK with the folly tags.

Thanks!
