### ISSUE TITLE
LengthFieldBasedFrameDecoder decoder Example. Not able to Read Content Length

### ISSUE THREAD

**Issue by sureshbalakundi** [facebook/wangle#61]
Im decoding LengthFieldBasedFrameDecoder  format. when I'm Decoding Length is not coming. Please Suggest me How i need to decode. please find the below program

class EchoHandler : public HandlerAdapter<std::string> {
 public:
  virtual void read(Context* ctx, std::string msg) override {
     LOG(INFO) << "Recieving Time";
/* Here Im Decoding the Buffer but Content Length is Not able to Read *//

    std::cout << "handling " << msg << std::endl;
    write(ctx, msg + "\r\n");
  }
};
class EchoPipelineFactory : public PipelineFactory<EchoPipeline> {
 public:
  EchoPipeline::Ptr newPipeline(std::shared_ptr<AsyncTransportWrapper> sock) {
    auto pipeline = EchoPipeline::create();
    pipeline->addBack(AsyncSocketHandler(sock));
    pipeline->addBack(LengthFieldBasedFrameDecoder());
    pipeline->addBack(LengthFieldPrepender());
    pipeline->addBack(StringCodec());
    pipeline->addBack(EchoHandler());
    pipeline->finalize();
    return pipeline;
  }
};

int main(int argc, char** argv) {
  google::ParseCommandLineFlags(&argc, &argv, true);

  ServerBootstrap<EchoPipeline> server;
  server.childPipeline(std::make_shared<EchoPipelineFactory>());
  server.bind(FLAGS_port);
  server.waitForStop();

  return 0;
}

**Comment by djwatson** [comment]
Set the "initialbytestostrip" to 0:

LengthFieldBasedFrameDecoder(uint32_t lengthFieldLength = 4,
                                        uint32_t maxFrameLength = UINT_MAX,
                                        uint32_t lengthFieldOffset = 0,
                                        int32_t lengthAdjustment = 0,
                                        uint32_t initialBytesToStrip = 0,
                                        bool networkByteOrder = true);
