### ISSUE TITLE
Build wangle encountered error: error: use of undeclared identifier 'malloc_usable_size'

### ISSUE THREAD

**Issue by ustczxf** [facebook/wangle#65]
When I tried to build wangle, it reported:
In file included from /project/opensource/source/wangle/wangle/../wangle/concurrent/ThreadPoolExecutor.h:19:
In file included from /project/opensource/source/wangle/wangle/../wangle/deprecated/rx/Observable.h:20:
/usr/local/include/folly/small_vector.h:619:14: error: use of undeclared identifier 'malloc_usable_size'
      return malloc_usable_size(u.pdata_.heap_) / sizeof(value_type);

I've built "folly" successfully, did anyone encounter the same issue?
Thanks!

**Comment by mohnishkodnani** [comment]
Yes I am getting the same issue. 
I was also able to compile folly without any issues. 
I am using MAC OS X 10.11.6 and gcc 6.
This is happening after pulling the latest master branch after about few months on both folly and wangle.

**Comment by mohnishkodnani** [comment]
It turns out it has something to do with jemalloc. 
when I checked the configure output of compiling folly it had checked and said malloc_usable_size yes but for malloc.h check it had said false. 
Then when I uninstalled jemalloc from my system , recompiled folly, it said malloc_usable_size as false and after this I could build wangle fine.

**Comment by ustczxf** [comment]
Thanks @mohnishkodnani , after I removed jemalloc, it works now.

**Comment by Allen5** [comment]
It still not work after i removed jemalloc from my system(OSX 10.12).

**Comment by YiqiuLiu** [comment]
I am having problem with this too. Installed folly with homebrew, got back luck with small_vector.h.

**Comment by anyflow** [comment]
I got the same problem. No difference with removing jemalloc, installing folly by homebrew / compiling source.

**Comment by howardzhang** [comment]
I am getting the same issue. 
My machine is OS X 10.12. 
Any update?

**Comment by anirudhvr** [comment]
folly/portability/Malloc.cpp provides a defintion for malloc_usable_size for apple platforms. Can you check why that code is not being executed on your platform (e.g., put a #error "check") inside the __APPLE__ guard.

**Comment by howardzhang** [comment]
@anirudhvr I was able to resolve this issue using @mohnishkodnani method. 

* Compile and install folly from source(mater branch) without jemalloc. (Note: Never use brew to install folly) 
* If you encounter any openssl issue, try apply patch https://github.com/facebook/folly/pull/513
* Then you may be able to compile wangle successfully.
