### ISSUE TITLE
Does not build due to removed getTFOSucceeded member of folly/io/async/AsyncSocket

### ISSUE THREAD

**Issue by spershin** [facebook/wangle#68]
Downloaded and built FB Folly
Now trying to build FB Wangle.
Build is broken because wangle code still uses getTFOSucceeded which was removed from folly/io/async/AsyncSocket on August 9. Can't believe this hasn't been noticed so far...

**Comment by siyengar** [comment]
This should exist now https://github.com/facebook/folly/blob/c1ad77a56bd725605154c4e71a852a3232b95481/folly/io/async/AsyncSocket.h#L446

**Comment by spershin** [comment]
What do you mean by 'should exist now'?
I'm getting the code by this command, this supposed to be the latest master, right?
git clone https://github.com/facebook/folly
And the function is not there.

**Comment by siyengar** [comment]
I have a feeling you're not building latest wangle against latest folly. We use the same code internally, so if this was broken, then we would have definitely noticed. What versions of folly and wangle are you using?

**Comment by spershin** [comment]
Ran "git clone https://github.com/facebook/folly" and built folly.
Ran "git clone https://github.com/facebook/wangle" and tried to build wangle.
Exactly what I did several days ago (maybe only I had a number of hours before two clone commands).

The error is now gone.
Thank you for the support!
I think this can be closed now.

**Comment by siyengar** [comment]
we sometimes do X-repository changes and there might be a slight delay between the time both the repos are synchronized. So waiting a little bit and trying again usually does the trick.
