### ISSUE TITLE
Installation: zstd reference not resolved

### ISSUE THREAD

**Issue by hcl14** [facebook/wangle#73]
While installing on Ubuntu 16.04 64-bit installation breaks with a number of errors:
```
recipe for target 'bin/ObservingHandlerTest' failed:
libfolly.so: undefined reference  to `ZSTD_initCStream'
...
```
etc... 

zstd-1.1.0 is installed, the libraries are located at `/usr/local/lib`.

**Fixed**: added manually to `CMakeLists.txt`:
```
LINK_DIRECTORIES(/usr/local/lib)
set(zstd_DIR "/usr/local/lib")

target_link_libraries(wangle
  ${FOLLY_LIBRARIES}
  ${Boost_LIBRARIES}
  ${OPENSSL_LIBRARIES}
  ${GLOG_LIBRARY_PATH}
  ${GFLAGS_LIBRARY_PATH} libzstd.so)
```

The installer still reports a warning about possible conflict:

```
/usr/bin/ld: warning: libzstd.so.0, needed by /usr/local/lib/libfolly.so, may conflict with libzstd.so.1
```

**Comment by Cyan4973** [comment]
Is it a double-installation issue ?

the older `zstd` version from Ubuntu in `/usr/bin/ld`, which is only `v0.5.1` hence is missing quite a few prototypes,
while the new `zstd` is within `/usr/local/lib`, is supposed to be `v1.1.0`, and therefore should work correctly ?

I suspect there are 2 `libzstd.so`, and the one selected is from the older installation, hence it targets `libzstd.so.0`.
The newer version should be `libzstd.so.1`.
Suggest to target this one instead.

**Comment by hcl14** [comment]
Yes, looks like the last warning was because of double installation issue, it was gone after I uninstalled everything connected with `zstd` and installed again new version from sources. Now the shortcut `libzstd.so` points to `libzstd.1.1.1024.so` and shortcut `libzstd.so.1` points to `libzstd.so.1.1.1`. 

However, a huge pile of `zstd` dependency issues for `libfolly` also appear when I try to install fbthrift (my final goal is fblualib), you can check [another](https://github.com/facebook/fbthrift/issues/186) my opened issue.
