### ISSUE TITLE
Does not have option for setting NextProtocolType

### ISSUE THREAD

**Issue by raeesbhatti** [facebook/wangle#75]
Folly has [option for setting](https://github.com/facebook/folly/blob/3272dfdbe243e0ac02acca1dd82bc391d1da079a/folly/io/async/SSLContext.cpp#L500-L503) the [NextProtocolType](https://github.com/facebook/folly/blob/3272dfdbe243e0ac02acca1dd82bc391d1da079a/folly/io/async/SSLContext.h#L355-L358) option which determines weather to use NPN, ALPN or both.
Google Chrome has dropped support for NPN, and only supports ALPN now, which means that HHVM Proxygen cannot serve the content using HTTP2 to Chrome.

`wangle::SSLContextConfig` should include an option to set NextProtocolType.

Related to facebook/hhvm#6822

**Comment by anirudhvr** [comment]
@raeesbhatti It defaults to NextProtocolType::ANY which should support ALPN. Are you finding this isn't the case?

**Comment by anirudhvr** [comment]
@raeesbhatti Still a problem? Please close out or provide more detail on what you need.

**Comment by raeesbhatti** [comment]
@anirudhvr The real problem was solved by compiling HHVM with OpenSSL 1.0.2 which supports ALPN. Thanks for your time.
