### ISSUE TITLE
https://github.com/facebook/wangle/blob/master/wangle/bootstrap/BootstrapTest.cpp#L354

### ISSUE THREAD

**Issue by banro21** [facebook/wangle#76]
May be I am ignorant, but when i run ctest it fails to create a socket. However when i change it 127.0.0.1, it works

ubuntu 14.0.4

**Comment by OliverMD** [comment]
I presume you are referring to

```
  SocketAddress localhost("::1", 0);
```

`"::1"` is the ipv6 loopback address. From my (limited) understanding this means that you don't have an ipv6 address bound to your loopback interface or ipv6 isn't enabled on your box.

You can check by running `ifconfig -a` and seeing what you have for the `lo` interface. For example on my machine I have ipv6 enabled and so I see the following for `lo`:

```
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1899 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1899 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:176876 (176.8 KB)  TX bytes:176876 (176.8 KB)

```

I suspect you will not see ` inet6 addr: ::1/128 Scope:Host`.

You can find out more about ipv6 on the ubuntu wiki article [IPv6](https://wiki.ubuntu.com/IPv6).

**Comment by banro21** [comment]
@OliverMD Thanks. I will try to with changing my VM configs.
