### ISSUE TITLE
undefined reference to `folly::symbolizer::installFatalSignalHandler()'

### ISSUE THREAD

**Issue by nevermatch** [facebook/wangle#77]
cmake -DBUILD_EXAMPLE=ON .
make 

[ 33%] Building CXX object CMakeFiles/BroadcastProxy.dir/example/broadcast/BroadcastProxy.cpp.o
[ 34%] Linking CXX executable bin/BroadcastProxy
/usr/local/lib/libfolly.so: undefined reference to `folly::symbolizer::installFatalSignalHandler()'
/usr/local/lib/libfolly.so: undefined reference to `folly::symbolizer::installFatalSignalCallbacks()'

g++ version:  g++ 4.9.3 or g++ 5.4.0 
git clone https://github.com/facebook/folly.git
git clone https://github.com/facebook/wangle.git

Thanks for the help

**Comment by lookenwu** [comment]
I met this problem too. Does anybody know how to fix this problem? Thanks.

**Comment by anirudhvr** [comment]
Thanks for the report. Have you updated your copy of folly to the latest version?

**Comment by anirudhvr** [comment]
Please close out if this is fixed after updating folly and wangle to latest.
