### ISSUE TITLE
Binary protocol example

### ISSUE THREAD

**Issue by kirillv** [facebook/wangle#79]
Hi all. Interested in this framework, but im a little bit confused how to parse binary messages (custom protocol etc) in proper "wangle" way). It would be cool if it would appear in example folder. Currently im using asio and everything ok, but as i can see wangle has more then 1 person behind (compare to asio).
Thanks in advance!

**Comment by anirudhvr** [comment]
The recommended way is to use folly::IOBuf and folly::Cursor. Here is an example of how we parse a TLS ClientHello message 

https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSSLSocket.cpp#L1648-L1735
