### ISSUE TITLE
getSSLClientSupportedVersions() is no more provieded by folly.

### ISSUE THREAD

**Issue by Laser-Cat** [facebook/wangle#80]

**Comment by anirudhvr** [comment]
Folly trunk indeed has this API. Please provide more info when opening issues, and why you opened this issue for the wangle project.

https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSSLSocket.h#L568

**Comment by Laser-Cat** [comment]
Sorry, I didn't see it
I encountered build error building wangle, which tells me the function does not exist.
It may be caused by me having too old or corrupted folly build
Sorry again for the inconvenience.
----- Original Message -----
