### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by romalin99** [facebook/wangle#82]
![image](https://cloud.githubusercontent.com/assets/6870144/21976145/5c05412e-dc0b-11e6-8798-b1a6e0e5b4a9.png)

**Comment by romalin99** [comment]
I can't compile the  EchoServer.cpp of Wangle
g++ -std=c++1y -o server EchoServer.cpp -Wl,-Bstatic -lwangle -Wl,-Bdynamic -lfolly  -lgflags -lpthread

**Comment by anirudhvr** [comment]
The OpenSSL version you're compiling with is too old and doesn't have TLS extension support. Please try with OpenSSL 1.0.2, which is now a marked as a minumum dependency in the README.
