### ISSUE TITLE
getSSLClientSupportedVersions removed

### ISSUE THREAD

**Issue by lizhanhui** [facebook/wangle#83]
Try to compile wangle against latest folly/master, it complains:

> wangle/acceptor/SSLAcceptorHandshakeHelper.cpp:66:43: error: no member named 'getSSLClientSupportedVersions' in 'folly::AsyncSSLSocket'

**Comment by bmatheny** [comment]
cc @siyengar

**Comment by anirudhvr** [comment]
@lizhanhui It's there alright. Are you sure you're picking up folly master? 
https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSSLSocket.h#L573

**Comment by lizhanhui** [comment]
Sorry, It's my fault using a branch that fell behind folly master.

Anyway, thanks for your quick reply.
