### ISSUE TITLE
How does one define paths for echo server ? Thanks

### ISSUE THREAD

**Issue by GuacheSuede** [facebook/wangle#86]

**Comment by anirudhvr** [comment]
What do you mean by 'paths'? Can you provide more detail on what you want to accomplish?

**Comment by GuacheSuede** [comment]
for example /user or /post to a certain handler

**Comment by anirudhvr** [comment]
Looks like you mean a HTTP handler. Wangle only provides the foundation for building servers/clients. Facebook's proxygen library, which builds on wangle and folly, is likely what you're looking for. There are some examples here - the echo server is the simplest: https://github.com/facebook/proxygen/tree/master/proxygen/httpserver/samples

**Comment by GuacheSuede** [comment]
@anirudhvr Thank you for the reference , there are however no paths example

**Comment by anirudhvr** [comment]
The echo example uses a very simple request handler that doesn't do much. You can take a look at RequestHandler internals and implemet your own that does different things based on paths. Here's an example of how to get a path from a request, though this specific example concentrates on HTTP2's push feature

https://github.com/facebook/proxygen/blob/master/proxygen/httpserver/samples/push/PushRequestHandler.cpp#L57

**Comment by GuacheSuede** [comment]
great, so i just adapt `    if(headers->getPath() == "/requestLargePush") {` to the echo handler ?

**Comment by anirudhvr** [comment]
Yes, pretty much, you can do this in the EchoHandler as well. The proxygen project has a mailing list as well where the devs are active if you have more questions on this.
