### ISSUE TITLE
In relation with proxygen and builiding http server

### ISSUE THREAD

**Issue by diorahman** [facebook/wangle#87]
What's the relation of this with proxygen? Can we build an http server based-on wangle?

**Comment by anirudhvr** [comment]
Yes, you can build an HTTP server using wangle acceptor and proxygen HTTP libraries. See examples here: https://github.com/facebook/proxygen/tree/master/proxygen/httpserver. Posting there or on the mailing list will get you the attention of proxygen devs.

**Comment by mitchberg-dailymotion** [comment]
Looking to do the same - use Wangle to process Http requests.  Does not look like there is an Http filter available (like Netty)?  Is the approach to use Proxygen to process Http protocol and the use Wangle filters down stream?
