### ISSUE TITLE
Test fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by LinusU** [facebook/wangle#9]
Lib | version
--- | ---
wangle | `v0.13.0`
folly | `v0.57.0`

```text
Test project /home/ubuntu/facebook/wangle/wangle
      Start  1: BootstrapTest
 1/11 Test  #1: BootstrapTest ....................   Passed    0.63 sec
      Start  2: OutputBufferingHandlerTest
 2/11 Test  #2: OutputBufferingHandlerTest .......   Passed    0.01 sec
      Start  3: PipelineTest
 3/11 Test  #3: PipelineTest .....................   Passed    0.01 sec
      Start  4: CodecTest
 4/11 Test  #4: CodecTest ........................***Failed    0.01 sec
      Start  5: CodelTest
 5/11 Test  #5: CodelTest ........................   Passed    0.40 sec
      Start  6: GlobalExecutorTest
 6/11 Test  #6: GlobalExecutorTest ...............   Passed    0.01 sec
      Start  7: ThreadPoolExecutorTest
 7/11 Test  #7: ThreadPoolExecutorTest ...........   Passed    0.72 sec
      Start  8: RxTest
 8/11 Test  #8: RxTest ...........................   Passed    0.01 sec
      Start  9: ServiceTest
 9/11 Test  #9: ServiceTest ......................***Exception: SegFault  0.13 sec
      Start 10: SSLCacheTest
10/11 Test #10: SSLCacheTest .....................***Failed    0.01 sec
      Start 11: SSLContextManagerTest
11/11 Test #11: SSLContextManagerTest ............   Passed    0.01 sec

73% tests passed, 3 tests failed out of 11

Total Test time (real) =   1.94 sec

The following tests FAILED:
	  4 - CodecTest (Failed)
	  9 - ServiceTest (SEGFAULT)
	 10 - SSLCacheTest (Failed)
```

**Comment by djwatson** [comment]
Tests disabled.  Thanks

**Comment by km4arr** [comment]
osx MacOS Sierra 10.12
5 - BootstrapTest (Failed)
7 - BroadcastPoolTest (Failed)

 Start  1: AcceptorTest
 1/22 Test  #1: AcceptorTest .........................   Passed    0.08 sec
      Start  2: ConnectionManagerTest
 2/22 Test  #2: ConnectionManagerTest ................   Passed    0.49 sec
      Start  3: LoadShedConfigurationTest
 3/22 Test  #3: LoadShedConfigurationTest ............   Passed    0.04 sec
      Start  4: PeekingAcceptorHandshakeHelperTest
 4/22 Test  #4: PeekingAcceptorHandshakeHelperTest ...   Passed    0.08 sec
      Start  5: BootstrapTest
 5/22 Test  #5: BootstrapTest ........................***Failed    0.77 sec
      Start  6: BroadcastHandlerTest
 6/22 Test  #6: BroadcastHandlerTest .................   Passed    0.04 sec
      Start  7: BroadcastPoolTest
 7/22 Test  #7: BroadcastPoolTest ....................***Failed    0.09 sec
      Start  8: ObservingHandlerTest
 8/22 Test  #8: ObservingHandlerTest .................   Passed    0.06 sec
      Start  9: AsyncSocketHandlerTest
 9/22 Test  #9: AsyncSocketHandlerTest ...............   Passed    0.04 sec
      Start 10: OutputBufferingHandlerTest
10/22 Test #10: OutputBufferingHandlerTest ...........   Passed    0.05 sec
      Start 11: PipelineTest
11/22 Test #11: PipelineTest .........................   Passed    0.84 sec
      Start 12: CodecTest
12/22 Test #12: CodecTest ............................   Passed    0.05 sec
      Start 13: AsyncTest
13/22 Test #13: AsyncTest ............................   Passed    0.08 sec
      Start 14: CodelTest
14/22 Test #14: CodelTest ............................   Passed    0.64 sec
      Start 15: GlobalExecutorTest
15/22 Test #15: GlobalExecutorTest ...................   Passed    0.11 sec
      Start 16: SerialExecutorTest
16/22 Test #16: SerialExecutorTest ...................   Passed    0.98 sec
      Start 17: ThreadedExecutorTest
17/22 Test #17: ThreadedExecutorTest .................   Passed    0.45 sec
      Start 18: ThreadPoolExecutorTest
18/22 Test #18: ThreadPoolExecutorTest ...............   Passed    3.67 sec
      Start 19: RxTest
19/22 Test #19: RxTest ...............................   Passed    0.03 sec
      Start 20: SSLContextManagerTest
20/22 Test #20: SSLContextManagerTest ................   Passed    0.03 sec
      Start 21: TLSCredProcessorTest
21/22 Test #21: TLSCredProcessorTest .................   Passed   20.03 sec
      Start 22: FilePollerTest
22/22 Test #22: FilePollerTest .......................   Passed    1.42 sec

91% tests passed, 2 tests failed out of 22
