### ISSUE TITLE
IO replication using wangle

### ISSUE THREAD

**Issue by jayesh-rao** [facebook/wangle#92]
Hi Guys,

Is it possible to use wangle to replicate IOs over to the peer node, in a HA (high-availability) setup?
If yes, are there any examples that we can refer to?

**Comment by snarkmaster** [comment]
I'm at best a casual user of wangle, but I bet that the reason you've had no replies to your question is that it's missing some of the essential details:
 - What exactly are you trying to do?
 - What are the bottlenecks?
 - Technical details of what you want wangle to be doing :)

Please reopen if you add some more detail.
