### ISSUE TITLE
Pipeline lifetime

### ISSUE THREAD

**Issue by debdattabasu** [facebook/wangle#94]
Hi. First of all, thank you for your awesome work. 
I am confused regarding pipeline lifetime in wangle. In ServerDispatcher, I see code that looks like this: 

  void read(Context* ctx, Req in) override {
    (*service_)(std::move(in)).then([ctx](Resp resp) {
      ctx->fireWrite(std::move(resp));
    });
  }

The future/promise pair holds a raw pointer to the Context, which I assume is owned by the pipeline. What happens if the connection is dropped? Who is responsible for destroying the channel pipeline? If the pipeline is destroyed by the ServerBootstrap, then the future callback may see a dangling context pointer. If the ServerBootstrap is not responsible for destroying the pipeline then who is? 

Regards.

**Comment by seiyap70** [comment]
template <typename Req, typename Resp = Req>
class ExecutorFilter : public ServiceFilter<Req, Resp> {
 public:
 explicit ExecutorFilter(
   std::shared_ptr<folly::Executor> exe,
   std::shared_ptr<Service<Req, Resp>> service)
      : ServiceFilter<Req, Resp>(service)
      , exe_(exe) {}

 folly::Future<Resp> operator()(Req req) override {
   return via(exe_.get()).then([ req = std::move(req), this ]() mutable {
     return (*this->service_)(std::move(req));
   });
  }

 private:
  std::shared_ptr<folly::Executor> exe_;
};

Same doubt for me, what if the executor the thread finished after the connection closed?I gdb the program, and did not find anyone call the pipeline destructor.

**Comment by seiyap70** [comment]
template <typename Req, typename Resp = Req>
class dump{
public:
	typedef typename HandlerAdapter<Req, Resp>::Context Context;
	
	~dump(){

		pipeline_ = NULL;
		ctx_ = NULL;
		std::cout<<"In dump"<<__FUNCTION__<<std::endl;
	}
	void foo(){
		std::cout<<"In dump"<<__FUNCTION__<<std::endl;
	}
	dump(Context* ctx,std::shared_ptr<PipelineBase> pipeline):ctx_(ctx), 
		pipeline_(pipeline)
	{
		
		std::cout<<"In dump"<<__FUNCTION__<<std::endl;
	}
	std::shared_ptr<PipelineBase> pipeline(){
		return pipeline_;
	}
	Context* context(){
		return ctx_;
	}
private:
	std::shared_ptr<PipelineBase> pipeline_;
	Context *ctx_;
};
template <typename Req, typename Resp = Req>
class SafeMultiplexServerDispatcher : public HandlerAdapter<Req, Resp> {
 public:

  typedef typename HandlerAdapter<Req, Resp>::Context Context;

  explicit SafeMultiplexServerDispatcher(Service<Req, Resp>* service)
      : service_(service) {}
  ~SafeMultiplexServerDispatcher(){
	  std::cout<<"In SafeMultiplexServerDispatcher "<<__FUNCTION__<<std::endl;

  }
  void read(Context* ctx, Req in) override {
	auto bone = std::make_shared<dump<Req, Resp>>(ctx, ctx->getPipelineShared());
    (*service_)(std::move(in)).then([bone = std::move(bone)](Resp resp) {
	   //ctx,this may had been freed, we should use someway to sync infomartion
	   auto pipe = bone->pipeline();
	   bone->context()->fireWrite(std::move(resp));
	   bone->context()->getTransport()->getEventBase()->runInEventBaseThread([pipe = std::move(pipe)]{/*nothing*/});
    });
  }

	virtual void readEOF(Context* ctx) {	
		ctx->getPipeline()->getPipelineManager()->deletePipeline(ctx->getPipeline());
		
  	}
  	virtual void readException(Context* ctx, folly::exception_wrapper e) {
    	ctx->getPipeline()->getPipelineManager()->deletePipeline(ctx->getPipeline());
  	}
 private:
  Service<Req, Resp>* service_;
};


Hi, this is my modify for MultiplexServerDispatcher. It works in my tests.

**Comment by debdattabasu** [comment]
This is similar to what I ended up doing. Any word from the official wangle developers? How is this expected to work in general in the original codebase?

**Comment by alexliyu7352** [comment]
It is seems not need, in the master code, 
when the socket shutdown, it will auto delete the pipline.
`folly::Future<folly::Unit> shutdown(Context* ctx, bool closeWithReset) {
    if (socket_) {
      detachReadCallback();
      if (closeWithReset) {
        socket_->closeWithReset();
      } else {
        socket_->closeNow();
      }
    }
    if (!pipelineDeleted_) {
      pipelineDeleted_ = true;
      ctx->getPipeline()->deletePipeline();
    }
    return folly::makeFuture();
  }`
