### ISSUE TITLE
production use status

### ISSUE THREAD

**Issue by noahdesu** [facebook/wangle#96]
I'm curious about the status of wangle with respect to its maturity. Is it being used in production (inside and/or outside fb), is the intention to support the project in the future? Thanks!

**Comment by bmatheny** [comment]
It's used extensively throughout Facebook. We continue to support it, but as with all our open source projects, folly/wangle aren't always in sync which sometimes leads to build or other issues. We do our best!

**Comment by noahdesu** [comment]
That's all the info I was looking for--out of sync is one thing, disappearing into bit rot is another :) Thanks!

**Comment by yfeldblum** [comment]
Note that we automatically tag, weekly, a mutually consistent set of revs in folly, wangle, fbthrift, and other repos.
