### ISSUE TITLE
Patch for fixing setThreadName

### ISSUE THREAD

**Issue by michaelaeriksen** [facebook/wangle#98]
From 9aecf3a4df921ff6a996dcdcb1493b7763989a92 Mon Sep 17 00:00:00 2001
From: "Michael A. Eriksen" <michael@abundantrobotics.com>
Date: Thu, 8 Jun 2017 15:39:25 -0700
Subject: [PATCH] fix for setting std::thread name

---
 wangle/concurrent/NamedThreadFactory.h | 6 ++++++
 1 file changed, 6 insertions(+)

diff --git a/wangle/concurrent/NamedThreadFactory.h b/wangle/concurrent/NamedThreadFactory.h
index b3f7f8b..f3d2fc2 100644
--- a/wangle/concurrent/NamedThreadFactory.h
+++ b/wangle/concurrent/NamedThreadFactory.h
@@ -28,9 +28,15 @@ class NamedThreadFactory : public ThreadFactory {
 
   std::thread newThread(folly::Func&& func) override {
     auto thread = std::thread(std::move(func));
+#if FOLLY_HAVE_PTHREAD
     folly::setThreadName(
         thread.native_handle(),
         folly::to<std::string>(prefix_, suffix_++));
+#else
+    folly::setThreadName(
+      thread.get_id(),
+      folly::to<std::string>(prefix_, suffix_++));
+#endif
     return thread;
   }
 
-- 
2.13.0.windows.1

**Comment by yfeldblum** [comment]
Too old. Please reopen as a PR if this is still an issue.
